import type { Metadata } from "next";
import Link from "next/link";
import Content from "./message.mdx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function Home() {
  return (
    <main>
      <Content />
      <ul>
        <li>
          <Link href="/about">about</Link>
        </li>
      </ul>
    </main>
  );
}
